### ISSUE TITLE
Create Maven plugin to run Orchid

### ISSUE THREAD

**Issue by cjbrooks12** [JavaEden/Orchid#100]
Make a Maven plugin to do all the same things the current Gradle plugin does, per suggestion on Reddit https://www.reddit.com/r/java/comments/85kiwr/introducing_orchid_a_new_static_site_generator/dvyrmm5/?context=1

**Comment by bjansen** [comment]
I'll give it a try!

**Comment by cjbrooks12** [comment]
Hmm, I'll have to investigate the transitive deps and get them smoothed out in the next release. And thanks for getting this going, its looking great! I'll check it out more over the weekend.

**Comment by bjansen** [comment]
Also, I noticed that both `orchidRun` and `orchidBuild` run the same command (`build`), is it intended?

**Comment by cjbrooks12** [comment]
`orchidRun` also accepts an `orchidRunTask` Gradle property to specify the task, which defaults to `build`. Usage would be like `gradle orchidRun -PorchidRunTask=serve`.
