### ISSUE TITLE
[suggestion] Add optional page hiding for drafts

### ISSUE THREAD

**Issue by altavir** [JavaEden/Orchid#141]
Add additional optional `publish` boolean flag on all pages with default to `true`. If `false`, then index, but do not render the page (or event do not index it). It will allow, to work on drafts or temporary hide parts of the site without physically removing the page.

**Comment by cjbrooks12** [comment]
The reverse of this variable already exists, pages have a `draft` variable which defaults to `false`, and setting it to `true` will prevent it from being rendered. See [Drafts](https://orchid.netlify.com/wiki/userManual/content/drafts) in the user manual.

I initially thought about including a `publish` variable in addition to `draft`, but then things would get confusing when both variables have opposing values (what do we do when a page is both a draft and set to publish?).
