### ISSUE TITLE
[maybe] Rename data directory into config

### ISSUE THREAD

**Issue by altavir** [JavaEden/Orchid#142]
It is cosmetic, but the data is data, it means something substantial in the directory. In fact is serves as a configuration. 

Since I work on scientific projects, I will probably want `data` name to be used for data in future (like some tables etc.).

**Comment by cjbrooks12** [comment]
The `data/` directory is set up to be used as both config and general data, and anything in it is available in the `config` global variable. But now that you bring it up, the naming does seem confusing, and it might make more sense to have separate `config/` and `data/` directory. I'll investigate this further, but I don't expect it to cause any major issues.
