### ISSUE TITLE
Posts implicitly depends on Taxonomies

### ISSUE THREAD

**Issue by altavir** [JavaEden/Orchid#149]
Trying to use posts without Taxonomies dependency results in 
```
[WARN] : Warnings:
[WARN] ModularList: 
[WARN] :     - OrchidComponent type [taxonomy] could not be found (on page '...' at ...)
...
```
Better to add it as explicit dependency.

**Comment by cjbrooks12** [comment]
All plugins are supposed to be completely independent, with no explicit or implicit dependency between any of them. I just checked and verified there is no implicit dependency from Posts to Taxonomies. 

Did you start from the OrchidStarter repo? If so, `data/posts.yml` includes a `postPages` property which adds config data to all the post pages. By default in the Starter repo, this is configured to add a `taxonomy` Component for tags and categories as an example of using [Archetypes](https://orchid.netlify.com/wiki/user-manual/configuration/page-config#archetypes).

**Comment by altavir** [comment]
Yes, this is the case. There is additional dependency case: admin page does not work without `OrchidPluginDocs` since admin templates are defined there.

**Comment by cjbrooks12** [comment]
yes, the admin panel comes from the OrchidPluginDocs plugin, as noted in the [Admin Panel wiki page](https://orchid.netlify.com/wiki/user-manual/configuration/admin-panel). The plumbing for local server-rendered pages is in core, but the admin panel itself is completely optional, and is only available if the OrchidPluginDocs plugin is included.

**Comment by altavir** [comment]
I see it now, but the confusion was caused by the fact that admin page is rendered even without the plugin, it just throws exception.

**Comment by cjbrooks12** [comment]
I think you're seeing the NetlifyCMS admin page when you don't have OrchidPluginDocs installed. NetlifyCMS is another plugin that adds a page at /admin and acts as a bridge between Orchid and NetlifyCMS by generating the CMS config based on the Orchid config. 

It seems like loading /admin without a trailing slash throws the following error (but this is an issue with the CMS, not Orchid):

```
Error loading the CMS configuration
The config.yml file could not be loaded or failed to parse properly.

Error message: Error: Failed to load config.yml (404)

Check your console for details.
```

**Comment by altavir** [comment]
I was trying to use `NetlifyCMS` without `OrchidPluginDocs`. In this case `baseUrl/admin` shows pebble insides and error is thrown about admin page template.

**Comment by cjbrooks12** [comment]
Which other plugins do you have included? I just tried that setup and didn't get any Pebble errors

**Comment by altavir** [comment]
Here is the dependency configuration:
```
dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    def orchid_version = '0.8.12'
    orchidCompile "io.github.javaeden.orchid:OrchidCore:${orchid_version}"
    orchidCompile "io.github.javaeden.orchid:OrchidNetlifyCMS:${orchid_version}"
    orchidCompile "io.github.javaeden.orchid:OrchidPages:${orchid_version}"
    orchidCompile "io.github.javaeden.orchid:OrchidPosts:${orchid_version}"
    orchidCompile "io.github.javaeden.orchid:OrchidWritersBlocks:${orchid_version}"
    orchidCompile "io.github.javaeden.orchid:OrchidTaxonomies:${orchid_version}"
    //orchidCompile "io.github.javaeden.orchid:OrchidPluginDocs:${orchid_version}"
}
```
`localhost:8080/admin` looks like this:
```
{% extends view.layout %}
--
  |  
  | {% block allContent %}
  | <iframe-refresh src="{{ site.baseUrl }}/admin/index.html"></iframe-refresh>
  | {% endblock %}
```

And error is thrown in IDE console:
```
Caused by: java.lang.IllegalArgumentException: Could not find template in list "[templates/server/admin/base.peb]"
	at com.eden.orchid.api.resources.ResourceServiceImpl.locateTemplate(ResourceServiceImpl.java:461)
```
