### ISSUE TITLE
Could not resolve plugin artifact 

### ISSUE THREAD

**Issue by cgorgulla** [JavaEden/Orchid#150]
I followed the tutorial of Orchid to build a first test site. I never used gradle before, and when I run it as written in the tutorial I get:

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/mnt/data/Dropbox/Coding/Webpages/OrchidTest/build.gradle' line: 12
> 
> * What went wrong:
> Plugin [id: 'com.eden.orchidPlugin', version: '0.8.10'] was not found in any of the following sources:
> 
> - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
> - Plugin Repositories (could not resolve plugin artifact 'com.eden.orchidPlugin:com.eden.orchidPlugin.gradle.plugin:0.8.10')
>   Searched in the following repositories:
>     Gradle Central Plugin Repository
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org

This was with gradle 4.8.1 With gradle 3.4.1 I get:

> 
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/usr/share/gradle/lib/gradle-base-services-3.4.1.jar) to method java.lang.ClassLoader.getPackages()
> WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/mnt/data/Dropbox/Coding/Webpages/OrchidTest/build.gradle' line: 12
> 
> * What went wrong:
> Error resolving plugin [id: 'com.eden.orchidPlugin', version: '0.8.10']
> > Could not GET 'https://plugins.gradle.org/api/gradle/3.4.1/plugin/use/com.eden.orchidPlugin/0.8.10'.
>    > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 

Maybe this is related to this issue here: https://github.com/gradle/gradle/issues/3326

**Comment by cjbrooks12** [comment]
Strange, I cannot reproduce this issue. Does it still break if you use Orchid's latest version `0.8.12` instead of `0.8.10` (change it both in the `plugins` and `dependencies` blocks)?

You could try replacing 

```groovy
plugins {
  // Apply the java-library plugin to add support for Java Library
  id 'java-library'
  id "com.eden.orchidPlugin" version "0.8.10"
}
```

with 

```groovy
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "gradle.plugin.com.eden:orchidPlugin:0.8.10"
    }
}

apply plugin: "java-library"
apply plugin: "com.eden.orchidPlugin"
```

If none of those seems to fix it, could you paste your whole `build.gradle` file here please?

**Comment by cgorgulla** [comment]
Thank you for your suggestions. I have tried all of them, but they did not work out unfortunately.

Here is my build.grade file:

>/*
>
> 
>  * This file was generated by the Gradle 'init' task.
>  *
>  * This generated file contains a sample Java Library project to get you started.
>  * For more details take a look at the Java Libraries chapter in the Gradle
>  * user guide available at https://docs.gradle.org/4.8.1/userguide/java_library_plugin.html
>  */
> 
> plugins {
>     // Apply the java-library plugin to add support for Java Library
>     id 'java-library'
>     id 'com.eden.orchidPlugin' version '0.8.10'
> }
> 
> dependencies {
>     // This dependency is exported to consumers, that is to say found on their compile classpath.
>     api 'org.apache.commons:commons-math3:3.6.1'
> 
>     // This dependency is used internally, and not exposed to consumers on their own compile classpath.
>     implementation 'com.google.guava:guava:23.0'
> 
>     // Use JUnit test framework
>     testImplementation 'junit:junit:4.12'
> }
> 
> // In this section you declare where to find the dependencies of your project
> repositories {
>     // Use jcenter for resolving your dependencies.
>     // You can declare any Maven/Ivy/file repository here.
>     jcenter()
> }
> 
> // 1. Include all official Orchid plugins and themes
> dependencies {
>     orchidCompile "io.github.javaeden.orchid:OrchidAll:0.8.10"
> }
> 
> // 2. Get Orchid from Jcenter, Bintray, and Jitpack
> repositories {
>     jcenter()
>     maven { url 'https://dl.bintray.com/javaeden/Orchid/' }
>     maven { url 'https://jitpack.io' }
> }
> 
> // 3. Use the 'BsDoc' theme, and view the site locally at 'http://localhost:8080'
> orchid { 
>     theme = "BsDoc"
>     baseUrl = "http://localhost:8080"
> }
>

**Comment by cjbrooks12** [comment]
I still can't reproduce the errors, even pasting the `build.gradle` file directly. Sounds like your issue might be related to the issue you linked, which looks to be network-related rather than Orchid or Gradle itself. Are you running it behind a proxy of some kind, maybe through a VPN? Or maybe you're offline? I don't know much about networking so I'm not quite sure what would be causing these network issues. 

I can get the error if I turn my wifi off completely, but that's to be expected, Gradle needs to be able to download the Orchid dependencies over the internet.

**Comment by cgorgulla** [comment]
Thank you for checking the file.

I'm directly connected via WiFi to the internet without VPN or proxy... really strange.

At least we could narrow down the problem... :-)
