### ISSUE TITLE
Add "Github Releases" publisher

### ISSUE THREAD

**Issue by cjbrooks12** [JavaEden/Orchid#179]
I've been using the [Travis CI Github Releases](https://docs.travis-ci.com/user/deployment/releases/) plugin for a while to push new releases to Github. But this plugin [has some serious flaws](https://github.com/travis-ci/dpl/issues/155) and I can only set the name of the release, not the release notes. I would like to have an Orchid publisher to create that release, so having automated releases is no longer dependent upon the CI platform, but bundled within Orchid itself, which can run on any CI platform.

This should be implemented as a new `OrchidPublisher` subclass in the `OrchidChangelog` plugin. It should use the current site version to find a Changelog entry, and then use that for the release name, and send the release notes as the body.

**Comment by yaroslavm** [comment]
Hi @cjbrooks12 , where new publisher should publish/send notes to?

**Comment by cjbrooks12** [comment]
It should be posting data directly to the Github API. The data to post should be the name and content of the current changelog version, similar to https://github.com/JavaEden/Orchid/blob/dev/plugins/OrchidChangelog/src/main/kotlin/com/eden/orchid/changelog/publication/RequiredChangelogVersionPublisher.kt. 

https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by yaroslavm** [comment]
@cjbrooks12 I pushed a publisher but still have several questions:
1. Do we still need default RequiredChangelogVersionPublisher.kt in changelog plugin?
2. I copied rate-limit handling from Netlify plugin: NetlifyPublisher#timeoutRateLimit. What is the better way to share this part of code?
3. How do you test plugins? I didn't find tests and also `./gradlew :plugins:OrchidChangelog:assemble` or similar from contributing manual doesn't work for me - build exists with successful status but did nothing.

**Comment by cjbrooks12** [comment]
Thanks for the work on this, I'm going over it now.

1) I think it makes sense to keep this around, for example if someone is hosting the project on Gitlab or somewhere else, but still wants to validate the changelog.
2) I don't think we would need the rate-limiting for this publisher. The NetlifyPublisher makes a separate HTTP request per-file it's uploading, so publishing a full site is likely to hit the limit just by itself. But creating a GitHub release is just a single HTTP call, so rate-limiting shouldn't be an issue. 
3) Orchid doesn't really have any good testing infrastructure set up yet. You should just set it up in the `OrchidCore` config as described [in this wiki page](https://orchid.netlify.com/wiki/user-manual/deployment/publication-pipeline), and then running `./gradlew :OrchidCore:orchidDeploy` will build the site and run the publishers.

**Comment by cjbrooks12** [comment]
Added in #185
