### ISSUE TITLE
Javadoc freezes indefinitely

### ISSUE THREAD

**Issue by almic** [JavaEden/Orchid#201]
I'm currently trying to use the Javadoc plugin, and so far everything runs fine. However, it gets stuck on the `Indexing [1000: javadoc]` part, and never progresses. I left it running for over 20 minutes and not much happened other than the initial `okHttpCache` files being created and the `javadoc` directory being created.

Funniest thing is that if I terminate the process with `Ctrl+C` when it hits the javadoc indexing part, the folder is populated with all the json files, which I assume just got frozen in memory for some reason and never properly saved until I stopped the build.

I can confirm that I can build the OrchidStarter example just fine, and all the files generate and I can start a local server. I'm using `orchidBuild` if that helps. I tried looking all over the place for solutions but nothing clear showed up.

**Comment by almic** [comment]
Just found this #199 and it looks like the same exact problem. Gonna leave this one up for now just because it half works when I stop it.

**Comment by cjbrooks12** [comment]
Yeah this is the same issue as #199, but I believe I have found the root cause and should have an update released later today after a bit more testing. The JSON files are actually just an intermediate format to get data from Javadoc to Orchid, not the Orchid site.

**Comment by cjbrooks12** [comment]
This should be fixed now in 0.12.17

**Comment by almic** [comment]
Looks like it works, thanks!
