### ISSUE TITLE
Consider replacing Guice with a faster DI lib

### ISSUE THREAD

**Issue by cjbrooks12** [JavaEden/Orchid#217]
Guice has served Orchid quite well, but its slow startup time makes me wonder if another DI lib could do better. As nearly all of Orchid's DI is just pure JSR-330 injection, it should be fairly easy to swap Guice out for another lib. I am interested in Kodein, but really have no idea how it will affect performance. Faster startup times are not worth slower overall build times.

**Comment by cjbrooks12** [comment]
The more I look into alternatives, the more I'm leaning toward [Koin](https://insert-koin.io/). It doesn't seem to support JSR 330 natively, but there might be an extension for it or something along those lines. It's API just seems to clean and natural, and would feel much less "magical" than Guice. Might help to move completely toward more of a pipeline/factory-driven API rather than purely declarative as it is now.

**Comment by jmfayard** [comment]
Koin is good, I am using it as well

**Comment by cjbrooks12** [comment]
Yeah, I've been using it more and more on my Android projects, it's really nice. The main blocker for using it here is a lack of support for multibindings. I've done some hacks to get something like it to work, but I'm waiting for a native multibindings solution to be implemented before making the change here.

**Comment by cjbrooks12** [comment]
Moved to #336
