### ISSUE TITLE
GroovyDoc plug-in

### ISSUE THREAD

**Issue by ericis** [JavaEden/Orchid#221]
Create a new plug-in for GroovyDoc

**Comment by cjbrooks12** [comment]
Just wanted to leave you a quick update on this front: I've managed to work my way into Groovy's Groovydoc APIs, and it's looking extremely promising! I'm getting back a full documentation model that looks almost identical to the Javadoc internal model, which is perfect, exactly what we need! Now that I'm able to access the model, it shouldn't be too much longer until it's all finished up and I could release this new plugin.

Progress for getting the Groovy model can be tracked in the [copper-leaf/dokka-json repo](https://github.com/copper-leaf/dokka-json/tree/features/groovydoc).

**Comment by cjbrooks12** [comment]
And another update here: the full integration of Groovydoc into Orchid went quite smoothly and the plugin is nearly complete! There are a few things left to touch-up, but I expect that it will be ready for release sometime later this week.

**Comment by cjbrooks12** [comment]
Alright, this plugin is now available in version 0.16.0! Give it a try and let me know if you have any issues with it. 

[Groovydoc plugin documentation](https://orchid.netlify.com/plugins/OrchidGroovydoc)

As I do not use Groovy myself it's likely that there may be certain edge cases that I missed that should be supported here, and in many cases the APIs provided by the Groovydoc tool were not implemented so may yield incorrect results. In either case, any feedback is greatly appreciated and I am happy to make any changes as needed.

Thanks for the suggestion for a great plugin!
