### ISSUE TITLE
Base URL not used in build output

### ISSUE THREAD

**Issue by drewsilcock** [JavaEden/Orchid#260]
I'm using Orchid with Maven and the Editorial theme, however the `baseUrl` configuration option doesn't seem to be used when using `mvn orchid:build`.

I can change the value in the configuration and the log prints out the correct value but the output HTML has the empty string `""` as the base URL.

This means that the base page works fine but any subdirectories don't correctly load the CSS or JS and the links are to the incorrect places.

This may be a problem with my configuration, but I can't seem to find a solution.

Thanks in advance!

## Info

**Version**: 0.16.6
**Orchid Config**: [config.yml](https://github.com/JavaEden/Orchid/files/3058864/config.yml.txt)
**Orchid build command log output**: [output.log](https://github.com/JavaEden/Orchid/files/3058867/output.log)
**Project POM**: [pom.xml](https://github.com/JavaEden/Orchid/files/3058868/pom.xml.txt)
**Output HTML**: [output_index.html](https://github.com/JavaEden/Orchid/files/3058865/output_index.html.txt)

**Comment by cjbrooks12** [comment]
I think that's a bug, all the configuration looks correct. I'll have to investigate this a bit more to know for sure what's going on.

**Comment by drewsilcock** [comment]
Thanks for the update, let me know if you've got any more questions about my setup or anything 🙂

**Comment by cjbrooks12** [comment]
Alright, I've got this bug fixed, a plain slash as the baseUrl should now work correctly. There were a number of places that needed to be patched, so let me know if you run into any issues with this moving forward. It's released in Version 0.16.9.

**Comment by drewsilcock** [comment]
Thanks Casey, just updated to 0.16.9 and it's correctly producing the right paths for all the resources. Thanks for the quick fix! 🙂
