### ISSUE TITLE
Javadoc auto generated documentation problem

### ISSUE THREAD

**Issue by alu0100888447** [JavaEden/Orchid#262]
Hi!

I tried to use orchid for my own project with the javadoc plugin. I have a java and I would like to know if I can auto generate the documentation in javadoc directly with the javadoc plugin and that it is published on the website. I followed the documentation, the tutorials and even then I did not get the javadoc plugin to generate anything. Could you tell me if orchid does this and if so, explain how?

Thank you

**Comment by cjbrooks12** [comment]
Orchid does not use the normal Javadoc tasks in Gradle, it handles that itself. It hooks into the Javadoc tool internally to get raw data, and then creates docs that look similar to [these](https://orchid.netlify.com/com/eden/orchid/Orchid) (these are Kotlin docs, but Java docs look and work pretty-much the exact same).

To get it set up, you'll need to add the `OrchidJavadoc` dependency to your `build.gradle` or `pom.xml` file:

```groovy
// build.gradle
dependencies {
    orchidRuntime 'io.github.javaeden.orchid:OrchidJavadoc:0.16.9'
}
```

```xml
<!-- pom.xml -->
<dependency>
	<groupId>io.github.javaeden.orchid</groupId>
	<artifactId>OrchidJavadoc</artifactId>
	<version>0.16.9</version>
	<type>pom</type>
</dependency>
```

After the dependency is added, Orchid will automatically detect it and start using it. You just need to tell Orchid where your Java source files are by adding the following snippet to your `config.yml` file:

```yaml
# config.yml
javadoc:
  args: empty list
  sourceDirs:
    - '../../main/java'
```

The `sourceDirs` is a list of file paths to document, which are _relative_ paths from your Orchid resources (the directory containing `config.yml`) to the root directory of your Java sources.

With those in place, you should be all set! Orchid will generate pages for all your classes and packages that follow the package structure of your code. Simply translating a fully-qualified class name to a folder structure will get you to that page's generated documentation. For example, a class `com.example.Foo` can be viewed at http://localhost:8080/com/example/Foo when running Orchid with `./gradlew orchidServe`.

**Comment by balta3** [comment]
Did you ever get it running? I get no javadoc generated, too. Even if I try the OrchidTutorials Project and start `./gradlew :java-site:docs:orchidServe` there is no javadoc generated at all, and all the API DOCS links have no href attribute

**Comment by cjbrooks12** [comment]
Do you have a repo I could look at to see why it's not working, or screenshots of the terminal output or webpages you're seeing so I can help identify the problem? 

I just ran the Javadoc sample from the OrchidTutorials repo's current master branch, and it worked just fine for me. Here are a couple screenshots I just took of the terminal output and the generated docs to demonstrate what you should be seeing:

**Terminal output (notice the `javadoc` row with 4 pages in the results table)**
<img width="846" alt="Screen Shot 2019-11-13 at 11 19 30 AM" src="https://user-images.githubusercontent.com/6157866/68787882-f305c200-0607-11ea-92c5-23be1fef9cc8.png">

**Locally-served output (on http://localhost:8080/com/example, and menu items are populated)**
<img width="1680" alt="Screen Shot 2019-11-13 at 11 19 53 AM" src="https://user-images.githubusercontent.com/6157866/68787950-10d32700-0608-11ea-95a2-2f5906fbde68.png">

If you're not getting that for your output, there are a couple of things to check:

1) What OS are you on? It might be an issue running Orchid on your particular OS
2) Do you have the JDK installed (not JRE)? You can try entering `javac -version` to be sure the JDK is installed. Also run `javadoc` in your terminal, which should be bundled with the JDK, as Orchid calls to that program internally to generate its Java docs.
3) What version of the JDK are you running on? The current release is only tested on JDK 8 and other versions may not work properly. (the current dev branch, and all future versions, are now tested on JDK 8, 9, 10, and 11, but this version has not been released yet).
