### ISSUE TITLE
KDoc does not render Java varargs correctly

### ISSUE THREAD

**Issue by DanySK** [JavaEden/Orchid#276]
I stumbled upon what seems to be a bug. I'm rendering the documentation for [this class](https://github.com/AlchemistSimulator/Alchemist/blob/master/alchemist/alchemist-implementationbase/src/main/java/it/unibo/alchemist/model/implementations/environments/Continuous2DEnvironment.java), whose relevant method is:
```java

    public Position makePosition(final Number... coordinates) {
        // stuff
    }
```

Dokka [renders the class badly at the moment](http://alchemist-unstable-doc.surge.sh/it/unibo/alchemist/model/implementations/environments/Continuous2DEnvironment.html) due to Kotlin/dokka#361. I will shortly update to Dokka 0.9.18 to see if that's solved.
I don't think it's related, since Orchid uses its own rendering engine, but there is no information stored for such vararg argument, [here](https://alchemistsimulator.github.io/latest/it/unibo/alchemist/model/implementations/environments/Continuous2DEnvironment/) is a rendered example.

**Comment by cjbrooks12** [comment]
This has been fixed in the [Kodiak](https://github.com/copper-leaf/kodiak) formatters as of [0.3.2](https://github.com/copper-leaf/kodiak/releases/tag/0.3.2), and work is underway to get Orchid integrated with the new Kodiak formatters. It will be available in the next major release.
