### ISSUE TITLE
Theme asset URLs getting creating with null/ prefix

### ISSUE THREAD

**Issue by singularsyntax** [JavaEden/Orchid#294]
Hello,

Orchid is creating incorrect URLs for assets for the Copper theme:

    

    
    
    

    
    
    
    
    
    
    

    
    
    

    
    <script>
        window.allData = {"reference":{"path":"","baseUrl":"null","fileName":"","extension":"html","usePrettyUrl":true,"link":"null"},"description":"","title":"Homepage"};
    </script>

    

    
    <link rel="stylesheet" type="text/css" href="null/Copper/5b4d6a27/assets/css/bulma.css"/>
    <link rel="stylesheet" type="text/css" href="null/Copper/5b4d6a27/assets/css/extraCss.css"/>
    <link rel="stylesheet" type="text/css" href="null/Copper/5b4d6a27/assets/css/bulma-tooltip.css"/>
    <link rel="stylesheet" type="text/css" href="null/Copper/5b4d6a27/assets/css/bulma-accordion.min.css"/>
    

These URLs, of course, do not exist, so the page does not get styled.

Please let me know what other debugging information I should provide.

Thanks.

**Comment by cjbrooks12** [comment]
Seems like the base URL is explicitly (probably accidentally) being set to null in the build script. Do you have a base URL set in your build script (`build.gradle`, `pom.xml`, or kscript script)?

**Comment by singularsyntax** [comment]
No, as the Maven template POM indicates that it is optional:

    
    <version>${project.version}</version>
    <baseUrl>${baseUrl}</baseUrl>

**Comment by singularsyntax** [comment]
If I set `baseUrl` to '/', it still doesn't work (though the asset URLs are rendered as absolute but without scheme/port/etc.). If I set it to the full production deployment URL (with scheme/domain/port), it works.

**Comment by cjbrooks12** [comment]
It should be optional, that's a bug with the Maven runner. I'll get a fix released for this tonight or tomorrow.

**Comment by cjbrooks12** [comment]
This issue has been resolved and is available in 0.17.2, thanks for reporting it!
