### ISSUE TITLE
Copyright text in config.yml

### ISSUE THREAD

**Issue by singularsyntax** [JavaEden/Orchid#298]
Orchid renders the page footer copyright mark with the value `{{ site.about.siteName }}`, so if I have a site named "The Orotund Orchid", the copyright text would be the same.

I'm not very well-informed about copyright law, but I've always understood it that a copyright must be assigned to an individual or a legally-recognized (i.e. corporate) entity. So I'm concerned that the copyright for a site with a name unrelated to an individual or for an unincorporated entity might not assert any legally valid ownership claim.

This is easily fixed by copying `templates/includes/footer.peb` into the corresponding place in an Orchid installation `resources` directory and modifying the copyright text as desired, but given that it's likely that it would need to be done often for multiple sites, I wonder if it would make sense to include the text in the `config.yml` data model:

    site:
      about:
        siteName: 'The Orotund Orchid'
        siteCopyright: 'The Orotund Orchid LLC'

And update `footer.peb` accordingly:

    <p class="copyright">
        &copy; {{ site.about.siteCopyright }}.
        ...
    </p>

**Comment by cjbrooks12** [comment]
Registering a copyright is optional, and any published work is automatically granted an implicit copyright, so I dont there are negative legal ramifications for assigning the copyright to an unincorporated organization. Regardless of the owner, it really should be registered to provide the best legal protection over the site contents. A more thorough explanation can be found on this [article from Legal zoom](https://www.legalzoom.com/articles/do-i-need-to-copyright-my-website).

That said, being able to set the copyright independently from the site name (but defaulting to the site name) is a great idea! I'll get this updated and a new version released in the next day or so for you.

**Comment by singularsyntax** [comment]
There's no hurry, whenever you find the time. Thanks!

**Comment by cjbrooks12** [comment]
This has just been released in version 0.17.3
