### ISSUE TITLE
Consider replacing Clog with Timber

### ISSUE THREAD

**Issue by cjbrooks12** [JavaEden/Orchid#304]
[JakeWharton/timber](https://github.com/JakeWharton/timber) offers nearly the same API as Clog (both were essentially ports of `android.util.Log`), and is currently/nearly a Kotlin/Multiplatform project, which means it could be used in normal JVM projects. By switching to that library, Orchid will be more adapted to a more industry-standard logger implementation, and then I will not need to maintain Clog any longer.

When using Timber, a Tree should be planted with, essentially, the custom loggers set up for Clog. For an initial implementation, it would probably be easiest to just pass the args directly from Timber through to Clog (so both libraries are in use for incremental migration, but the intended API usage is Timber).

**Comment by lyrafelipe** [comment]
@cjbrooks12 Hello!

As far as I can tell there isn't someone working on this issue, so I will take it. :wink: 

I will open a Pull Request as soon as possible.

**Comment by cjbrooks12** [comment]
Moved to #336
