### ISSUE TITLE
Why uppercase name for artifacts?

### ISSUE THREAD

**Issue by thekalinga** [JavaEden/Orchid#311]
Java convention is to use hiphenated-lowercase for artifact names, i.e

`OrchidCore` should have been `orchid-core`
`OrchidSourceDoc` should have been `orchid-source-doc`

Is there any reason why you chose to use CamelCase convention for artifact names?

**Comment by cjbrooks12** [comment]
No good reasons, anyway 😅

I guess when I first started working on Orchid, I wasn't aware of the convention. Now it would be a lot of work to change the artifacts to match the convention with very little benefit to it.

Eventually, I will probably want to change the group ID too, once I've got a proper domain for this project, and I will update the artifact IDs at that time as well. But that would likely come when it's time for a proper version 1.x, fully stable and the core set of APIs for building themes and plugins is feature-complete.

But that's still a long way away, so I've just continued with the uppercase convention to keep the artifact names consistent within this project.
