### ISSUE TITLE
maven-plugin terminates maven build process

### ISSUE THREAD

**Issue by spind42** [JavaEden/Orchid#312]
If the orchid plugin is executed as one of many maven-plugins during a maven build. The maven-plugin is terminating the whole maven-process. So no further maven-plugins/modules are executed afterwards. 

I am going to make a pr which should solve this issue.

**Comment by cjbrooks12** [comment]
This fix has been released in [0.17.5](https://github.com/JavaEden/Orchid/releases/tag/0.17.5)
