### ISSUE TITLE
external extraCss support

### ISSUE THREAD

**Issue by daudazimkhan** [JavaEden/Orchid#317]
For multiple orchid projects, we have to put assets e.g. assets/css/orchidKotlindoc.scss in each project's resources. It would be nice to allow external extraCss so that we dont have to keep duplicates.
something like the following should work
extraCss:
      - '../../../../../common-doc/assets/css/orchidKotlindoc.scss'

Right now it says

<pre><font color="#C4A000">[WARN] </font>Warnings:
<font color="#C4A000">[WARN] </font>AssetHolderDelegate: 
<font color="#C4A000">[WARN] </font>    - ../../../../../common-doc/assets/css/orchidKotlindoc.scss is not a valid CSS asset, perhaps you are missing a /assets/css/orchidKotlindoc-&gt;css Compiler extension?
</pre>

**Comment by cjbrooks12** [comment]
That is supposed to work, it looks like a bug parsing the file path. I'll have to dig a little more on this.

**Comment by cjbrooks12** [comment]
This is a similar root problem to your other issue with the wiki file paths, and the solution will behave similarly. Adding assets will no longer check for "proper" file extensions, and then the referenced asset will resolve to the given filename with the relative path segments removed.

**Comment by cjbrooks12** [comment]
This bug has been fixed in [0.17.6](https://github.com/JavaEden/Orchid/releases/tag/0.17.6).

**Comment by daudazimkhan** [comment]
Thanks a lot!
