### ISSUE TITLE
suppressing dokka documentation for specific classes

### ISSUE THREAD

**Issue by daudazimkhan** [JavaEden/Orchid#320]
Dokka supports suppressing specific classes from documentation e.g.
```
packageOptions {
  prefix = "com.fqdn.MyPackage.R"
  suppress = true
}
```
The above will exclude `com.fqdn.MyPackage.R` from the generated documentation. Using orchid, is there any way to do the same?

**Comment by cjbrooks12** [comment]
Not currently but it is in the works and is intended for the next major release (0.18.0), along with a bunch of other improvements to all the code documentation plugins. I'll close this issue as a duplicate, but you can follow #288 for the existing issue on this feature.
