### ISSUE TITLE
Orchid Forms examples

### ISSUE THREAD

**Issue by singularsyntax** [JavaEden/Orchid#327]
Hello,

Are there any examples of Orchid Forms in use? I'm trying to setup a form, but I'm not seeing the `__onSubmit` hidden field with return redirect URL when I submit the form.

Thanks.

**Comment by cjbrooks12** [comment]
It looks like the docs are a bit out of date, sorry about that. The condition for `__onSubmit` should be added when a `redirectionPage` is specified on the form definition, not when the `action` is missing. 

The `redirectionPage` is a PageRelation, so can just be a page title, or can be an object with `itemId`, `collectionType`, or `collectionType` attributes.

Try a form definition like the following:

```
title: 'Contact Us'
redirectionPage: 'Thank You'
fields:
  ...
```

**Comment by singularsyntax** [comment]
That worked. Thanks.
