### ISSUE TITLE
Share docs without deploy and Gradle

### ISSUE THREAD

**Issue by ViTVetal** [JavaEden/Orchid#386]
It is possible to share generated docs without deploy and Gradle? Something like sharing generated files from the build folder. I tried open index.html from the build folder but UI is ugly.

**Comment by cjbrooks12** [comment]
You can run `./gradlew orchidBuild` to generate the site and share the build folder, but it doesn't support loading directly from the filesystem. But you can use any normal fileserver application such as [http-server](https://github.com/http-party/http-server) to serve and view the site locally without Gradle.
