### ISSUE TITLE
Question: link from wiki to kotlin doc

### ISSUE THREAD

**Issue by ola-adolfsson-ipex** [JavaEden/Orchid#387]
Hi, 

First, thanks for a great tool!

We're using the kotlindoc to document our code and the WIKI plugin to tie everything together. Now to the questions, is there a "proper" way to link to the kotlinc doc from the WIKI using itemID or similiar? 

This is how we do it now in one mark down file:
`used through the [DummyLink](../../kotlindoc/api-dummy-component`

We would like to remove the `../../` if that is possible? Using the itemId? 

Thanks

**Comment by cjbrooks12** [comment]
Yes, the proper way is to use the [linking functions](https://orchid.run/wiki/user-manual/core-concepts/internal-links) to create those links. The `itemId` for Kotlindoc pages is the class name you want to link to (both simple and fully-qualified class names are supported).
