### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by DanySK** [JavaEden/Orchid#397]
Hi,
is this project still actively maintained?

**Comment by cjbrooks12** [comment]
No, Orchid is not dead. My personal life got unexpectedly busy over the last year, but Orchid is not dead. I am currently, slowly, doing work behind-the-scenes to get Orchid republished on MavenCentral. You can read the full announcement on the Orchid blog

https://orchid.run/news/2021-5-13/whats-up-with-orchid

**Comment by DanySK** [comment]
I'm happy to know that your life is getting richer and the project is still ongoing. I was asking because I have one large project whose documentation is entirely managed via Orchid, plus I had been writing a number of modules (e.g., `OrchidForScience`) and I wanted to intercept possible issues with continued maintenance early on, as switching away (to hugo I presume) would be difficult. Since the tool works so well, I am considering moving to Orchid other projects too, but before committing I wanted to be sure the tool has a future.

Also, Orchid is fantastic and really deserves huge success.
