### ISSUE TITLE
Question: analytics 

### ISSUE THREAD

**Issue by ola-adolfsson-ipex** [JavaEden/Orchid#401]
Hi,

Firstly, thanks for a great product and the time and effort you put into it :) . 

I've looked through the documentation and closed/open issed in the search for a way to add a google analytics script. We would like to know which parts of our documentation are most used. 

Should we create a customer plugin? Or is there an easier way?

Thanks
Ola

**Comment by cjbrooks12** [comment]
Currently, there's no official plugin for adding the whole GA snippet, but you can add it as an "extra JS" asset pretty easily, [documentation here](https://orchid.run/wiki/user-manual/core-concepts/assets#extra-js-configuration).

However, this would be a very welcome addition, and I'd gladly accept a PR if you wanted to add it. It might be a little while until I could actually get it merged and deployed, but if you're interested, I can give you some additional help and guidance in getting it added.
